### PR TITLE
Update gradles, lots of improvements

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Update gradle wrapper to 7.2 using git bash

### 2nd commit
- Have gradle build not fail if release_gradle.properties doesn't exist
- Drastically reorganize the build.gradle files
- Update AGP 3.5.4 -> 7.0.2
- Close https://github.com/LightDestory/FastHub-RE/issues/3 by using gradlePluginPortal

### 3rd commit
- Add AndroidX Preference library
- Migrate a single android.preference.* that was somehow left over
- Remove deprecated preferenceOverlay (uses newer by default)

### 4th commit
- Update Apollo 1.2.2 -> 1.3.3 ([changelog](https://github.com/apollographql/apollo-android/releases))
- Remove unused Apollo imports
- (I'm not sure if everything in `onCompilationUnit` is needed)

### 5th commit
- Update Apollo 1.3.3 -> 2.5.9 ([changelog](https://github.com/apollographql/apollo-android/releases))
- Fix Apollo deprecations
- Remove wrong extra constructor

### 6th commit
- Make a TON of miscellaneous QoL improvements
- Fixed a bunch of deprecations

### CODE REVIEW

**Comment by LightDestory** [comment]
Thanks for your contribution,  I will test as soon as I can

**Comment by TacoTheDank** [comment]
> Thanks for your contribution, I will test as soon as I can.
> 
> Is it ready to be merged?

Should be, yes.

**Comment by LightDestory** [comment]
I treid your branch and I am unable to build the project.
 I have first tried my usual "working" setup using Android Studio 4.1.3 but the IDE warns me that the Android Plugin is unable to open such project and suggests me to try AS 2020.3.1 or newer.

I have installed that version but the build fails on kapt due to a ReflectionError.

Am I missing some settings or similar?

**Comment by TacoTheDank** [comment]
Nothing should be missing, I think. Should I try downgrading to 4.2.2 for now?

**Comment by LightDestory** [comment]
> Nothing should be missing, I think. Should I try downgrading to 4.2.2 for now?
Hmm I tried with both Android Studio 4.1.3 and Android 2020.3.1 I get the same error.

Hmm, maybe there is some idea settings that I am now awere of. 
I have just downloaded the latest Android Studio and imported your repository:
- Kotlin 1.5.0 (but the gradle still uses the 1.4.32)
- JDK 11 (built-in)
- Clean cache & local maven indexing

I just run the build procedure and it will fail on kaptDebugKotlin with error java.lang.reflect.invocationtargetexception complaining about missing symbol such as Commit, User, ect.

My Android Studio is 100% vanilla, as-is post-installation. Do you have any particular settings?

**Comment by ponthamaya** [comment]
@TacoTheDank hi, it's failed to compile on 7.0.2.

**Comment by LightDestory** [comment]
I tried every setup I could think of to get this PR to compile but I am still unsuccessful. Due to upcoming exams I am getting less and less time to experiment with the code, but I am giving max priority to this kind of issue, i am pushing back some fixes because I really want to get rid of the "Android Studio 4.1.2" limit.

**Comment by TacoTheDank** [comment]
@LightDestory The thing is, I get the same compilation errors. I just ignored all those errors because I thought I was just missing something from MY build.

This app is a damn mess lol. I'll see if I can figure out how to make it work, but I have no guarantees.

**Comment by zeromake** [comment]
@LightDestory @TacoTheDank 
my [FastHub](https://github.com/zeromake/FastHub/tree/migration_kotlin) is Apollo up to 3.1.0，deprecation lombok more:
see [change](https://github.com/zeromake/FastHub/tree/migration_kotlin#fork-change--plan-list)

The workload is huge, interested can carry it yourself, I plan to carry some modifications from this side. There are also some bugs, but now, most of them are working properly

**Comment by LightDestory** [comment]
> @LightDestory @TacoTheDank my [FastHub](https://github.com/zeromake/FastHub/tree/migration_kotlin) is Apollo up to 3.1.0，deprecation lombok more: see [change](https://github.com/zeromake/FastHub/tree/migration_kotlin#fork-change--plan-list)
> 
> The workload is huge, interested can carry it yourself, I plan to carry some modifications from this side. There are also some bugs, but now, most of them are working properly
> 
> 947 files changed: [compare](https://github.com/zeromake/FastHub/compare/development...zeromake:migration_kotlin)

You are doing a GOD tier work to put your hand on such old code base, I tried to make it work but it was a mess everytime.

I am still learning Kotlin but I will check your changes. Can I slowly cherry pick them?

**Comment by zeromake** [comment]
@LightDestory 

my fasthub is already, not has obvious, now test it pr reply

**Comment by LightDestory** [comment]
> @LightDestory
> 
> my fasthub is already, not has obvious, now test it pr reply
> 
> click reply right top menu easy trgger scrolling.

I will try as soon as I can.

What do you except to do from this point?

**Comment by LightDestory** [comment]
Closing this PR, the time has come to get it working :)

**Comment by TacoTheDank** [comment]
I appreciate @zeromake's work to pick up where I couldn't :)
